print ("Seja bem vindo ao QUIZZ do ENGLISH!")
print ("Nesse jogo você tara que responder traduzindo para o Inglês algumas palavras em português, você iniciara esse jogo com 5 corações, se seus corações chegar a 0 você voltara do inicio!")
coração = (5)
p1 = input("Traduza EU SOU/EU ESTOU para o INGLÊS.") 
if p1 : ("I AM")